# Generated by Django 2.1.9 on 2019-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0003_pagina_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
