# Generated by Django 2.1.9 on 2019-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0004_auto_20190620_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='palavra',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
